first try
Qolit3/algorithm-and-data-structure pull request #1
Opened 2023-03-01 23:22 UTC by Qolit3

2023-03-02 06:22 UTC, andryxxa93 requested changes
Здравствуйте!
Работа проделана огромная 👍 

- Отлично типизировали проект
- Хорошо сделаны классы
- Хорошо сделали визуализацию

но есть некоторые недочеты: 

- [x] Файл app.test.js нужно удалить, так как он не относится к проекту
- [x] app.css нужно сделать модулем app.module.css, а в компоненте использовать модульные классы, а не строки
- [x] По заданию в Сортировке массива, Стеке, Очереди и Связанном списке необходимо вешать лоадер на активную кнопку , а все остальные дизейблить. 
<img width="1440" alt="Снимок экрана 2023-03-02 в 09 08 20" src="https://user-images.githubusercontent.com/60173362/222345237-14eb0aab-1070-4e51-8180-e9cc7e5d1943.png">

- [ ] По заданию все кнопки сабмита должны быть неактивными, если в инпуте ничего нет или в нем невалидные данные.

<img width="1440" alt="Снимок экрана 2023-03-02 в 09 10 57" src="https://user-images.githubusercontent.com/60173362/222345665-f470de21-2c61-4264-9df9-d32619fbc8bc.png">

- [x] При невалидном индексе кнопки активны. Нужно определять максимально возможный индекс по длине массива минус 1
<img width="834" alt="Снимок экрана 2023-03-02 в 09 13 23" src="https://user-images.githubusercontent.com/60173362/222346024-e6baa7d6-a0a9-4bfd-9c17-fbc3f441a995.png">

- [ ] В Связаном списке при удалении по индексу у кнопок бесконечно крутится лоадер. 

https://user-images.githubusercontent.com/60173362/222346382-01bf6c6f-2cae-493b-9362-3da29b9292b3.mov

 - [ ] В стеке если очистить элементы, а потом попытаться добавиться новый, то появятся несколько старых.
  
https://user-images.githubusercontent.com/60173362/222346782-4ddf2235-4839-4ece-81a2-a4a51b7b13eb.mov

- [ ] В Очереди если добавить элементы, а потом очистить, то новые элементы будут добавлять по индексу на котором остановились предыдущие. Должно начать добавляться сначала.

https://user-images.githubusercontent.com/60173362/222347465-cbf16c30-1c09-4a11-a08d-80b2a791cde2.mov

Удачных правок!

2023-03-03 16:08 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-04 12:48 UTC, gennady-bars reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Работа проделана огромная



* Все юнит-тесты (32 шт) проходят успешно
* Все `snapshots` (15 шт) успешны
* Все cypress-тесты проходят успешно

но есть некоторые недочеты: 

* Если в инпуте есть `onChange` или `onInput`, то в этом же инпуте должен быть атрибут `value`.
* В чек-листе есть пункт: при **открытии** страницы `Сортировка массива` генерируется случайный массив и отображается на странице
* Любой `JSX` нужно оборачивать в `круглые скобки`, чтобы избежать проблем с автоматической вставкой точек с запятой
* Скрин https://disk.yandex.ru/i/jVVigl93OTKsag в инпуте для индекса разрешены только цифры. Нужно `type="number"` в инпуте указать
* `http://localhost:3000` повторяется несколько раз в коде тестов. Нужно вынести в константу `testUrl`, чтобы можно было одним движением изменить урл для тестов
А можно в документации посмотреть, как настроить быстро `baseUrl` для cypress https://docs.cypress.io/api/commands/visit#Visit-is-automatically-prefixed-with-baseUrl 
* `'div[class*="circle_circle"]'` дублируется 17 раз
* Если **строка-селектор** повторяется более 2х раз в коде, значит, этот селектор нужно выносить в **константу**, чтобы можно было одним движением изменить его и не искать по всему коду дублирования этого селектора.



Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте **работоспособность проекта** и наличие возможных ошибок в консоли браузера (кнопка `F12`) перед отправкой на ревью. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний `Нужно исправить`.

Удачного рефакторинга кода.

2023-04-04 12:48 UTC, gennady-bars commented on src/components/queue-page/queue-page.tsx
> +  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
**Можно лучше**

Можно сделать универсальный **кастомный** хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = (event) => {
    const {value, name} = event.target;
    setValues({...values, [name]: value});
  };
  return {values, handleChange, setValues};
}

```

Этот код помещают в отдельный файл `useForm.js` в папке `hooks` и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```jsx
  const {values, handleChange, setValues} = useForm({});

```

2023-04-04 12:48 UTC, gennady-bars commented on src/components/string/string.tsx
> +            onChange={handleInputChange}
Если в инпуте есть `onChange` или `onInput`, то в этом же инпуте должен быть атрибут `value`.

Именно так контролируются компоненты в Реакте.

Контролируемые компоненты (`useState, value, onChange`)
подробнее про это: https://ru.react.js.org/docs/forms.html

2023-04-04 12:48 UTC, gennady-bars commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          onChange={handleInputChange}
Если в инпуте есть `onChange` или `onInput`, то в этом же инпуте должен быть атрибут `value`.

Именно так контролируются компоненты в Реакте.

Контролируемые компоненты (`useState, value, onChange`)
подробнее про это: https://ru.react.js.org/docs/forms.html

2023-04-04 12:48 UTC, gennady-bars commented on src/components/queue-page/queue-page.tsx
> +          return <Circle
`          return <Circle
`

Любой `JSX` нужно оборачивать в `круглые скобки`, чтобы избежать проблем с автоматической вставкой точек с запятой - такое иногда бывает при компиляции


```jsx

        {fibonachiArr.map((item, index) => {
          return ( <========= Круглые скобочки =========
            <Circle
              key={index}
              letter={`${item}`}
              extraClass={styles.circle}
              tail={`${index}`}
            />
          ); <========= Круглые скобочки =========
        })}

```


Это можно сделать комбинацией клавиш `SHIFT + ALT + F` или с помощью `prettier`

2023-04-04 12:48 UTC, gennady-bars commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          return <Circle
`          return <Circle
`

Любой `JSX` нужно оборачивать в `круглые скобки`, чтобы избежать проблем с автоматической вставкой точек с запятой - такое иногда бывает при компиляции


```jsx

        {fibonachiArr.map((item, index) => {
          return ( <========= Круглые скобочки =========
            <Circle
              key={index}
              letter={`${item}`}
              extraClass={styles.circle}
              tail={`${index}`}
            />
          ); <========= Круглые скобочки =========
        })}

```


Это можно сделать комбинацией клавиш `SHIFT + ALT + F` или с помощью `prettier`

2023-04-04 12:48 UTC, gennady-bars commented on cypress/e2e/fibonacchi.cy.ts
> +    cy.visit('http://localhost:3000/fibonacci');
`http://localhost:3000` повторяется несколько раз в коде тестов. Нужно вынести в константу `testUrl`, чтобы можно было одним движением изменить урл для тестов
А можно в документации посмотреть, как настроить быстро `baseUrl` для cypress https://docs.cypress.io/api/commands/visit#Visit-is-automatically-prefixed-with-baseUrl

2023-04-04 12:48 UTC, gennady-bars commented on cypress/e2e/fibonacchi.cy.ts
> +    cy.get('div[class*="circle_circle"]').as('circle');
`'div[class*="circle_circle"]'` дублируется 6 раз

2023-04-04 12:48 UTC, gennady-bars commented on cypress/e2e/list.cy.ts
> +    cy.get('p[class*="circle_index"]').as('circle-index');
`'p[class*="circle_index"]'` 4 раза дублируется


и так далее

2023-04-05 22:58 UTC, gennady-bars approved these changes
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2023-04-19 10:37 UTC, merged